language: node_js

node_js:
  - 'stable'

cache:
  npm: false

jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script: jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage

install:
  - npm ci

script:
  - npm run lint
  - npm run test:ci
